### ISSUE TITLE
How is this any different to Electron only without security measures?

### ISSUE THREAD

**Issue by Therewasherefor** [Digital-Sapphire/PyUpdater#107]
?
Are Desktop applications still a thing?

**Comment by tysondogerz** [comment]
@dariusisbackbaby123  One is Desktop, one is Webapp.  That is how it is different.  They are about as good as each other.  Desktop is generally cheaper as it uses clients resources though.  There is only support for SCP and Amazon so you'll find atm it can get expensive if you get rogue client or troll.   The only real issues are security, it needs: https://github.com/theupdateframework/tuf and free alternatives.  Otherwise it is golden.  Electron is plenty hackable but the fact that you build it around a server and no source code means its the go to method.

**Comment by JMSwag** [comment]
I cannot say as I've never used Electron.
