### ISSUE TITLE
Build two versions of an application from one directory

### ISSUE THREAD

**Issue by wbinek** [Digital-Sapphire/PyUpdater#114]
Hi!

I wonder if it is possible to build two versions of an application from the same directory using PyUpdater. I need to have 64 and 32 bit versions of an application. Previously I had two PyInstaller spec files which I called from proper python versions. Now I would like to use PyUpdater. Can I init two repositories with different names and urls in one directory?

Thanks for any help!

**Comment by Devligue** [comment]
I am not sure how on windows but on Linux PyUpdater creates `nix.spec` file for 32 bit and `nix64.spec` for 64 bit. It depends on which version of Python (32 or 64 bit) you are using PyUpdater I guess.

For Linux it is certainly possible but you probably need to make use of virtualenvs with different versions of Python. It should be similar for windows.

**Comment by wbinek** [comment]
Sorry for the late response. Yes I am using different versions of python to build an app.

On windows there is always win.spec created, but i can rename the file. 

I don't know how to deal with PyUpdater config files. Can I use the same application name and url for both versions? Therefore configure PyUpdater once using any Python version and the use two versions for building? Or I should initialise the PyUpdater twice for each Python version (wouldn't it override some files)?

**Comment by Devligue** [comment]
If regardless of Python version there is always `win.spec` then I don't think you can do much about it. If you rename it (to `win64.spec` for example) you should also change names inside it (the `name='win'` argument). Try then building your app and see if it worked (i.e. check if the package is named correctly, and everything works fine).

Yes you can use same application name and url for both versions as long as their package names are different (for example: `yourApp-win-1.0.0.zip` and `yourApp-win64-1.0.0.zip`) but since the package naming is somewhat automatic in PyUpdater then I can't guarantee that it will work if you build it with your custom-named .spec file.

EDIT:
By the way why do you need 64 and 32 bit versions of an application? You can run the 32 bit version on both 32 and 64 bit machines. And as far as I know unless your app is doing some heavy stuff you won't benefit from 64 much, in fact it might just make your app use more resources without reason.

**Comment by wbinek** [comment]
Thanks again for the feedback. 

In fact you are absolutely right, I can drop the 64 bit version. I started developing my app for 64 bit system, then I needed to make the 32 bit version for an older pc, so I created two separate versions. However I can make 32 bit only :) Thanks!

**Comment by JMSwag** [comment]
@wbinek On windows it'll have to be either 32 or 64bit.
