### ISSUE TITLE
Small Changes Produce Large Patch Sizes

### ISSUE THREAD

**Issue by riq-dfaubion** [Digital-Sapphire/PyUpdater#121]
I want use PyUpdater for a project that will run on a fleet of bandwidth constrained machines.

**Summary:**
On my mac, if I create a `hello_world.py` file 40 bytes in size, and create a pyupdater package `updatertest-mac-0.0.1.tar.gz`, then change a single byte in `hello_world.py` and generate a `updatertest-mac-0.0.2.tar.gz` and `updatertest-mac-2`, the `updatertest-mac-2` file is 2.5mb large.

I understand why the version files are large, everything needs to be packed to ensure consistent cross-machine execution, but I need the patch files to be smaller (when reasonable). 

**Random Investigation and Speculation:**
As a test, I unpacked both the tars and `diff`'d each of the files in them.  The only file that was different was my application file (I would argue that the library files aren't changing 90% of the time).  

I created a bsdiff for each file between the unpacked updatertest-mac-0.0.1.tar.gz and the unpacked updatertest-mac-0.0.2.tar.gz, and tar.gz'd the bsdiffs together.  The resulting file was 3.3K in size.  

This suggests to me that there's an easy way to encapsulate all the info that represents a patch in a smaller file size.

**Suggestion:**
At packaging time, create both styles of patch files, if the new style patch is smaller, keep both. Updaters that understand the concatenated-individual-file-patch type update file can opt-in to downloading an applying the new-style patch instead of the old-style patch files.

**Comment by schulmenueplaner-de** [comment]
I am having the same issue, with a ubuntu 16.04 python 3.5 packaged wxpython application, application is 40mb one byte change patch is 35mb.
Patch size on windows with the same app / same change is about 120kb.

The problem seems to relate to tar + gzip vs. .zip.
tar+gzip throws everything into one archive and then compresses the archive,
 zip compresses file by file and puts it into an archive afterwards.

--> bsdiff4 seems to be much more efficient on the seperately compressed files on .zip archives.

I have hacked pyupdater/utils/__init__.py to use .zip on linux as well,
 and the patch size (same change as above) is about 750kb now (not perfect but much better than 35mb) --> but the update process does not work 100% on unix if .zip is used -->  

I am getting a:

Traceback (most recent call last):
  File "main.py", line 374, in checkIfUpdateAvailable
  File "pyupdater/client/updates.py", line 603, in extract_restart
  File "pyupdater/client/updates.py", line 704, in _restart
  File "pyupdater/client/updates.py", line 163, in process
  File "pyupdater/client/updates.py", line 166, in _restart
  File "os.py", line 583, in execl
PermissionError: [Errno 13] Permission denied

--> I guess the +x is missing, so that needs more work...

**Comment by JMSwag** [comment]
@schulmenueplaner-de gzip was used on linux & mac to prevent the +x issue. Any ideas on how we might resolve this?

**Comment by schulmenueplaner-de** [comment]
@JMSwag 

Maybe try to store the file permissions separately using:
```
retrieve permissions:
find ./ -exec getfacl {} \; > pyupdater_meta_permissions.txt

and after the applying the patch:
setfacl --restore=pyupdater_meta_permissions.txt
```

**Comment by JMSwag** [comment]
I’ll try to work on this if no PRs come up anytime soon.

**Comment by JMSwag** [comment]
PR #184 allows specifying a file format. Updating the permissions, once extracted, will be left to the implementor. I'll accept any PRs which add this functionality.

**Comment by mnauf** [comment]
I am having the same issue. I followed this [tutorial](https://pyupdater-wx-demo.readthedocs.io/en/latest/overview.html#running-from-source). My file size for version 0.01 is 473M and for version 0.02, 473M, both of them are too large as compared to what they show in the demo, which is 14 MB. Also, the patch size is 431M, even though I haven't changed anything in version 2 except the version number.

**Comment by elamathis18** [comment]
Hi, sorry to comment on old posts, but I am having the same issues with version sizes upto 100MB and the patch files at 75MB. Are there any workarounds available?

**Comment by schulmenueplaner-de** [comment]
@mnauf  @elamathis18 

I assume you are both using Linux ?

Did you specify "zip" as --archive-format ?

```usage: pyupdater build [opts]<script>
optional arguments:
  -h, --help            show this help message and exit
  --archive-format {zip,gztar,bztar,default}
  ```

**Comment by elams18** [comment]
No, I'm using windows.

And also, after packaging and signing, doesn't it produce a .zip as a default?

**Comment by elamathis18** [comment]
No, I'm using windows.
It produces the file in .zip format after packaging and signing by default.

**Comment by schulmenueplaner-de** [comment]
@elamathis18 
hm, that is strange, the above Problem applies to Linux 
(Windows = small patch size    and    Linux = huge patch size)

Just an idea, have you tried to disable "signing" and checked the patch file size ?

The patch file size seems to depend on how well the binary diff is working
on the archived files.
