### ISSUE TITLE
It would be nice to offer github release integration

### ISSUE THREAD

**Issue by linzuzeng** [Digital-Sapphire/PyUpdater#125]
[electron.build ](https://www.electron.build/auto-update) offers built-in support for using github releases as the update server. 

And I comes with a nice CI support which automatically [publishs the realease](https://www.electron.build/configuration/publish) when the build finishes.

It would be nice if PyUpdater could offer some similar feature :)

**Comment by JMSwag** [comment]
@linzuzeng I've added support for custom downloaders which will allow a user to implement a downloader that can communicate with the mentioned service and similar services. PyUpdater has support for upload plugins.

**Comment by JMSwag** [comment]
See [Usage | Client | Advanced](https://www.pyupdater.org/usage-client-advanced/#use-your-own-file-downloader) for implementation details.

**Comment by JessicaTegner** [comment]
Hi.
Not to bomb old issues, but has anyone implemented a github release updater plugin / download?

**Comment by JMSwag** [comment]
If anyone has implemented the github release upload plugin, it would be great if they'd open a PR to add a link in the docs ;)

**Comment by JMSwag** [comment]
@NicklasMCHD No worries, better than opening a new issue :)

**Comment by diVineProportion** [comment]
I'll try to take a look at just how the update check works. I remember seeing a get or put request on my local server when having pyupdater look to 127.0.0.1. Does it just take the current version of the frozen py and += 1 to the version, then check for patch/full (next version) match against all files in the directory listing?

Was thinking about messing around with using a github repo as the 'directory listing' and using the `?raw=true` url param, but not sure how the update check would go.

**Comment by JessicaTegner** [comment]
@diVineProportion  did you ever figure something out.

**Comment by diVineProportion** [comment]
@NicklasTegner 

Sort of. Right now I can use a github repository (separate from my project or within a different branch of my project) to host the keys, versions and update files. I didn't mess with trying to grab them from assets/releases page yet. I feel that if it is possible to host in the releases page, it would be more in tune with a plugin rather than hosting them in a repo, seems a bit tacky.

```
    UPDATE_URLS = ['https://github.com/owner/repo/raw/branch/',
                   'https://github.com/owner/repo/blob/branch/',
                   'https://raw.githubusercontent.com/owner/repo/branch/']
```

Haven't spent the time to figure out which one of these is the golden ticket, maybe more than one would work.

For simplicity, the hosting in repo would be ideal, as the files can always be accessed from the same URL. If hosted in release, you could fetch the latest from the github api, but that would mean you would have to have prereleases and all in one release tag, or do some serious work under the hood. Not on my todo list at the moment, but the repo version definitely works, put it in a private repo maybe or a separate branch, works great
