### ISSUE TITLE
User path with accent

### ISSUE THREAD

**Issue by lachauj** [Digital-Sapphire/PyUpdater#88]
Hello,

I recently noticed that after a update with a user which have an accent on Windows, pyupdater can't find and launch invis.vbs.

There is a setting with sys to use utf-8 instead of ascii.
```
import sys

reload(sys)
sys.setdefaultencoding('utf-8')
```
Thank you for your help

**Comment by JMSwag** [comment]
Hi @lachauj, If this is still an issue for you, please create a PR. I can assist if needed.

**Comment by lachauj** [comment]
Alright I'm going to try to find the best way to fix that

**Comment by 2press** [comment]
I am not sure, but I think one of my users encountered a similar problem as well. After an app-update this message was shown:

![eykpfrh7mv0](https://user-images.githubusercontent.com/26044736/38204747-684a2b26-36a4-11e8-9e8c-909cd9dcc168.jpg)

I don't speak Russian, but this message apparently reads that the executable to be updated wasn't found. I am assuming that  pyupdater was unable to copy the executable from the download location to it's proper directory due to the Russian characters in the directories name.

**Comment by 2press** [comment]
I would guess that my issue can be fixed my adding `encoding='utf-8-sig'` or `encoding='utf-8'`to the `open` calls that generate the bat-file:

 https://github.com/JMSwag/PyUpdater/blob/4067f9e05f3d1aa7cdec79296824c69cb7510545/pyupdater/client/updates.py#L170

https://github.com/JMSwag/PyUpdater/blob/4067f9e05f3d1aa7cdec79296824c69cb7510545/pyupdater/client/updates.py#L190

https://github.com/JMSwag/PyUpdater/blob/4067f9e05f3d1aa7cdec79296824c69cb7510545/pyupdater/client/updates.py#L202

https://github.com/JMSwag/PyUpdater/blob/4067f9e05f3d1aa7cdec79296824c69cb7510545/pyupdater/client/updates.py#L229

**Comment by 2press** [comment]
The initial issue might be circumvented by using the `appdirs package`: https://github.com/ActiveState/appdirs

**Comment by JMSwag** [comment]
Fixed in a036c5548205265bb043b25f56ee703bdf422edf
