### ISSUE TITLE
Critical bug: Do not ever try to erase anything outside the app!

### ISSUE THREAD

**Issue by cbenhagen** [Digital-Sapphire/PyUpdater#91]
If `current_app == '/Applications/YourAPP.app'` this will (try to) erase all your apps:
https://github.com/JMSwag/PyUpdater/blob/686992ca638bc2afffe55fb44bb97b2b16fe0c4c/pyupdater/client/updates.py#L675-L676

**Comment by JMSwag** [comment]
@cbenhagen Thanks for the report. I'll work on this.

**Comment by moscoquera** [comment]
hi, i haven't faced this issue yet(?), if i understand correctly, **rmtree** is trying to remove everything inside your **/Application** folder?

**Comment by cbenhagen** [comment]
Correct

**Comment by cbenhagen** [comment]
@JMSwag if this can't be fixed quickly I would strongly suggest to revert the commit and release a new version to pypi. Deleting the data of our users customers/users is probably the worst bug this project can have. Just imagine what happens if someone releases an update with this code and then gets complaints from hundreds of people who got their apps deleted. Or wherever they had your app laying around. Could be their Downloads folder, their desktop.. 

Also we should absolutely create regression tests for this and think about how we can prevent such bugs in the future. Maybe we create a wrapper around rmtree?

**Comment by moscoquera** [comment]
Hi again, the solution should be simple as detect if **current_app** is a directory or not, also is necessary to add some assertion in the test because this still passing the tests on my VM.

I will work on it tomorrow

Update 2: i think the root of the bug  is the use of the windowed mode on mac, i'm rewriting the tests to allow windowed mode to find a better solution for this.

Update 3: fixes  and windowed tests looks promising on mac, still need to run travis.

**Comment by cbenhagen** [comment]
@JMSwag please do something about this issue!!! Test and merge https://github.com/JMSwag/PyUpdater/pull/94 or roll back to 2.4.1. But the current situation is dangerous and does shed a very bad light on the project.

**Comment by JMSwag** [comment]
@cbenhagen @moscoquera I'll jump on this tonight after work. Apologies for the delay.

**Comment by JMSwag** [comment]
Fixed in #94
