### ISSUE TITLE
Travis: Run tests on macOS

### ISSUE THREAD

**Issue by cbenhagen** [Digital-Sapphire/PyUpdater#92]

**Comment by moscoquera** [comment]
is python supported on travis's macOS image?

https://github.com/travis-ci/travis-ci/issues/2312

i tried when was doing the directory support, but wasn't able to make it work.

NVM: i just found a workaround, i'll play a little with it.

**Comment by cbenhagen** [comment]
@moscoquera sorry did not see your edit in time..

**Comment by moscoquera** [comment]
i'm stuck on something.... fixes are working on linux, windows and osx. but travis fails because its trying to run the tests on python 3.4 and 3.5 on osx. and those are not available AFAIK. is there a way to disable 3.4 and 3.5 only for osx?
this's the travis build for osx: https://travis-ci.org/moscoquera/PyUpdater

**Comment by JMSwag** [comment]
@cbenhagen @moscoquera Travis does not support python on Mac. https://github.com/travis-ci/travis-ci/issues/9026
